<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

        <gazebo>
          <plugin name='skid_steer_drive' filename='libgazebo_ros_diff_drive.so'>
            <ros></ros>
            <update_rate>10</update_rate>
            <num_wheel_pairs>2</num_wheel_pairs>
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <left_joint>rear_left_wheel_joint</left_joint>
            <right_joint>rear_right_wheel_joint</right_joint>
            <wheel_separation>0.235</wheel_separation>
            <wheel_separation>0.235</wheel_separation>
            <wheel_diameter>${wheel_radius*2.0}</wheel_diameter>
            <wheel_diameter>${wheel_radius*2.0}</wheel_diameter>
            <max_wheel_torque>1.5</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
          </plugin>
        </gazebo>
        <!-- publish joint states -->
        <gazebo>
          <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
            <joint_name>front_left_wheel_joint</joint_name>
            <joint_name>front_right_wheel_joint</joint_name>
            <joint_name>rear_left_wheel_joint</joint_name>
            <joint_name>rear_right_wheel_joint</joint_name>
          </plugin>
        </gazebo>
</robot>